// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFK1IBgzp5pNb4NmoHN-kKfjtpR1f6tfo',
    appId: '1:850009013603:web:479dd584afa52bdd5d6756',
    messagingSenderId: '850009013603',
    projectId: 'technician-platform-42948',
    authDomain: 'technician-platform-42948.firebaseapp.com',
    storageBucket: 'technician-platform-42948.firebasestorage.app',
    measurementId: 'G-GLB64JKJK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCislfLxYCr6thuCFK3zyk8WIObdqix1Do',
    appId: '1:850009013603:android:4560f1d07b17609d5d6756',
    messagingSenderId: '850009013603',
    projectId: 'technician-platform-42948',
    storageBucket: 'technician-platform-42948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNe9HogKeV_JZWi4PYiq1oO71u-FhOOdI',
    appId: '1:850009013603:ios:2c159eacedcf9abd5d6756',
    messagingSenderId: '850009013603',
    projectId: 'technician-platform-42948',
    storageBucket: 'technician-platform-42948.firebasestorage.app',
    iosBundleId: 'com.example.technicianServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNe9HogKeV_JZWi4PYiq1oO71u-FhOOdI',
    appId: '1:850009013603:ios:2c159eacedcf9abd5d6756',
    messagingSenderId: '850009013603',
    projectId: 'technician-platform-42948',
    storageBucket: 'technician-platform-42948.firebasestorage.app',
    iosBundleId: 'com.example.technicianServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFK1IBgzp5pNb4NmoHN-kKfjtpR1f6tfo',
    appId: '1:850009013603:web:b2caa10c5c5a5f4f5d6756',
    messagingSenderId: '850009013603',
    projectId: 'technician-platform-42948',
    authDomain: 'technician-platform-42948.firebaseapp.com',
    storageBucket: 'technician-platform-42948.firebasestorage.app',
    measurementId: 'G-P0JW7LNDRR',
  );
}
